### ISSUE TITLE
Replace category to module in ext_emconf.php

### ISSUE THREAD

**Issue by gaumondp** [Quebecca/qc_info_rights#4]
Right now it says "plugin" which translate to "Frontend Plugin" on TER. That is not the right category.

Should be set to "module".

See: https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/DeclarationFile/Index.html

**Comment by taieb123** [comment]
Thank you, for the reporting, i already solve this issue in the last update.
